[package]
name = "cargo-purge"
version = "0.1.0"
authors = ["Quentin Gruber <quentingruber@gmail.com>"]
repository = "https://github.com/QuentinGruber/cargo-purge"
description = "remove global crates.io registry"
license = "MIT"
edition = "2018"
[dependencies]
whoami = "1.1.2"
